package sctrcd.payments.rules

import com.sctrcd.payments.facts.*

global java.util.List countryList;


rule "Trigger BIC validation."
    no-loop
when
    $req: PaymentValidationRequest($payment:payment, payment.bic != null)
    not BicValidationRequest(bic == $payment.bic)
then
   insert( new BicValidationRequest($payment.getBic()) );
end


rule "Trigger IBAN validation."
when
    $req: PaymentValidationRequest($payment:payment, payment.iban != null)
    not IbanValidationRequest(iban == $payment.iban)
then
    insert(
        new IbanValidationRequest($payment.getIban())
    );
end
